app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

    #codemaster_mailup:
    #resource: "@MailupBundle/Resources/config/routing.yml"
    #prefix: "/mailup"

    #guzzle: clients: codemaster_mailup: base_url: "https://services.mailup.com"