<?php

namespace AppBundle\Entity;

/**
 * ChiamateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiamateRepository extends \Doctrine\ORM\EntityRepository
{
}
