<?php

namespace AppBundle\Entity;

/**
 * UtentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtentiRepository extends \Doctrine\ORM\EntityRepository
{
}
